services:
  postgres:
    container_name: postgres-sql-fastprod
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: fastprod
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - fastprod
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-fastprod
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  fastprod:
    driver: bridge

volumes:
  postgres:
    driver: local