spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastprod
    username: postgres
    password: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  keycloak:
    realm-url: http://localhost:8182/realms/fastprod

keycloak:
  admin:
    server-url: http://localhost:8182
    client-secret: fastprod-backend-local-secret

application:
  file:
    uploads:
      file-output-path: ./uploads
  frontend:
    url: http://localhost:8001

logging:
  level:
    com.vertyll.fastprod: DEBUG
