spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    clean-disabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

security:
  keycloak:
    realm-url: ${KEYCLOAK_REALM_URL}

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

application:
  mail:
    from: ${MAIL_FROM}
  file:
    uploads:
      file-output-path: ${FILE_UPLOAD_PATH}
  frontend:
    url: ${FRONTEND_URL}

logging:
  level:
    root: WARN
    com.vertyll.fastprod: INFO
