spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    clean-disabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

security:
  jwt:
    access-token:
      secret-key: ${JWT_ACCESS_SECRET}
    refresh-token:
      secret-key: ${JWT_REFRESH_SECRET}
  cookie:
    secure: true

application:
  file:
    uploads:
      file-output-path: ${FILE_UPLOAD_PATH}
  frontend:
    url: ${FRONTEND_URL}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  first-name: ${ADMIN_FIRST_NAME}
  last-name: ${ADMIN_LAST_NAME}

app:
  seed:
    enabled: ${APP_SEED_ENABLED}

logging:
  level:
    root: WARN
    com.vertyll.fastprod: INFO
