spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastprod
    username: postgres
    password: postgres
  mail:
    host: localhost
    port: 1025

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  keycloak:
    realm-url: http://localhost:9000/realms/fastprod
    admin:
      server-url: http://localhost:9000
      client-secret: fastprod-backend-local-secret
  mail:
    from: no-reply@fastprod.local
  file:
    uploads:
      file-output-path: ./uploads
  frontend:
    url: http://localhost:8001

logging:
  level:
    com.vertyll.fastprod: DEBUG
