spring:
  application:
    name: fastprod-frontend
  profiles:
    default: local

server:
  port: 8001
  shutdown: graceful
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 10h
      cookie:
        name: FASTPROD_SESSION
        http-only: true
        secure: true
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.vertyll.fastprod

keycloak:
  client-id: fastprod-frontend

logging:
  level:
    org.atmosphere: WARN
