server:
  servlet:
    session:
      cookie:
        secure: false

api:
  backend:
    url: http://localhost:8080/api/v1

keycloak:
  realm-url: http://localhost:9000/realms/fastprod
  client-secret: fastprod-frontend-local-secret
  app-url: http://localhost:8001

logging:
  level:
    com.vertyll.fastprod: DEBUG
