spring:
  application:
    name: fastprod-frontend
  profiles:
    default: local

server:
  port: 8001
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.vertyll.fastprod

security:
  jwt:
    access-token:
      expiration: 900000
      refresh-before-expiry: 120000
    refresh-token:
      cookie-name: refresh_token

logging:
  level:
    org.atmosphere: WARN
