api:
  backend:
    url: http://localhost:8080/api/v1

keycloak:
  realm-url: http://localhost:8182/realms/fastprod
  client-secret: fastprod-frontend-local-secret
  app-url: http://localhost:8001

logging:
  level:
    com.vertyll.fastprod: DEBUG
